title: LeetCode 75

author:
  name: Joel Castillo
  email: jocastillo@colmex.mx

theme: minima
#remote_theme: jekyll/minima@1e8a445

plugins:
  - jekyll-feed
  - jekyll-seo-tag

social_links:
  - title: Repository at GitHub
    icon: github
    url: "https://github.com/JoelCae/leetcode-75"
