# Site settings
title: LeetCode 75
email:
description: 
baseurl: https://github.com/JoelCae/leetcode-75/
url: https://joelcae.github.io/leetcode-75/
twitter_username:
github_username:  JoelCae

# Build settings
markdown: kramdown
permalink: pretty
