title: LeetCode 75

author: 
  name: Joel Castillo
  email: jocastillo@colmex.mx

description: >
  This is my leetcode75 journey


#theme: minima
remote_theme: jekyll/minima@1e8a445

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  social_links:
    - title: Github repository
      icon: github
      url: "https://github.com/JoelCae/leetcode-75"
    - title: LinkenId
      icon: linkenid
      url: "www.linkedin.com/in/joel-castillo-espinosa"


